sh test.sh fixed_test/assign.cpp int y
sh test.sh fixed_test/at_const.cpp int y
sh test.sh fixed_test/at.cpp int y
sh test.sh fixed_test/bidirect_it.cpp int y
sh test.sh fixed_test/copy_construct.cpp int y
sh test.sh fixed_test/erase.cpp std::string y
sh test.sh fixed_test/insert.cpp int y
sh test.sh fixed_test/insert2.cpp int y
sh test.sh fixed_test/ite_arrow.cpp foo y
sh test.sh fixed_test/ite_eq_ope.cpp foo y
sh test.sh fixed_test/ite_n00.cpp int y
sh test.sh fixed_test/ite_n1.cpp int y
sh test.sh fixed_test/ite.cpp int y
sh test.sh fixed_test/push_pop.cpp std::string y
sh test.sh fixed_test/relation_ope.cpp int y
sh test.sh fixed_test/rev_ite_const.cpp int y
sh test.sh fixed_test/rite_arrow.cpp int y
sh test.sh fixed_test/rite_eq_ope.cpp int y
sh test.sh fixed_test/rite.cpp int y
sh test.sh fixed_test/rite2.cpp int y
sh test.sh fixed_test/size.cpp int y
sh test.sh main_vector.cpp int y